In [1]:
import numpy as np
import pandas as pd

# remember, to quickly see pandas content you can type pd.<tab 

# and to see pandas documentation hit pd?

In [2]:
pd?

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
data[1]

0.5

In [7]:
data[0]

0.25

In [8]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [9]:
data[1::2]

1    0.5
3    1.0
dtype: float64

# main difference with Pandas Series and NumPy array: Numpy array has an implicitly defined integer index, whereas, Pandas Series have an explicitly defined index associated with the values

# for example, the explicit index can be anything, including not an integer

In [10]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index =['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [11]:
data['b']

0.5

# we may also use nonsequential or non- continuous indices

In [13]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index=[2, 5, 4, 12])
data

2     0.25
5     0.50
4     0.75
12    1.00
dtype: float64

In [14]:
data[5]

0.5

In [17]:
#data[3]=> won't work since there's no index for 3

## in a sense, we can think of a Pandas Series being capable of having specialization of a Python dictionary.

In [19]:
population_dict = {'California': 38500000,
                  'Texas': 26000000,
                  'New York': 20000000,
                  'Florida': 19000000,
                  'Illinois': 12000000}
population = pd.Series(population_dict)
population

California    38500000
Texas         26000000
New York      20000000
Florida       19000000
Illinois      12000000
dtype: int64

# by default, a Series will be created where the index is drawn

In [20]:
population['California']

38500000

## unlike a dictionary, the Series supports array-styled operations, including slicing

In [22]:
population['California':'New York']

California    38500000
Texas         26000000
New York      20000000
dtype: int64

In [25]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

#### ifit's a list or NumPy array, the index defaults to an integer sequence

In [27]:
pd.Series(5, index=[100, 200, 300]) #scalar => repeated to fill the specified index

100    5
200    5
300    5
dtype: int64

In [29]:
pd.Series({2:'a', 1:'b', 3:'c'}) #data can be a dictionary

2    a
1    b
3    c
dtype: object

In [30]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2]) #the index can be explicitly set, if wished

3    c
2    a
dtype: object

# Next, let's investigate the DataFrame

# if Series are thought of as one-dimensional arrays with flexible indices and row, a DataFrame can be thought of as a two-dimensional array with both flexible row indices and flexible column names

In [31]:
area_dict = {'California': 424000, 'Texas': 700000, 'New York': 142000, 'Florida': 170000, 'Illinois': 150000}
area = pd.Series(area_dict)
area

California    424000
Texas         700000
New York      142000
Florida       170000
Illinois      150000
dtype: int64

In [33]:
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    38500000  424000
Texas         26000000  700000
New York      20000000  142000
Florida       19000000  170000
Illinois      12000000  150000

In [36]:
states.index #index labels

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [37]:
states.columns #index holding column labels

Index(['population', 'area'], dtype='object')

### allas, the DataFrame can be thought of as a generalization of a two-dimensional NumPy array, where both rows and columns have generalized index for accessing the data

# it's also important to think of the DataFrame as a specialization of a dictionary. Where the dictionary maps the key to a value, the DataFrame maps a column name to a Series of column data

In [38]:
states['area']

California    424000
Texas         700000
New York      142000
Florida       170000
Illinois      150000
Name: area, dtype: int64

# *** Think of DataFrames as Generalized Dictionaries, NOT Generalized Arrays ***

## thinking more about this, it's because if we take the 0th column, there's still data in there. We think about the column titles as indices.

In [39]:
pd.DataFrame(population, columns=['population'])

population
California    38500000
Texas         26000000
New York      20000000
Florida       19000000
Illinois      12000000

In [44]:
data = [{'a': i, 'b': 2 * i, 'c' : 5 * i, 'd' : i ** i}
       for i in range(4)]
pd.DataFrame(data) #can form a list of dictionaries

a  b   c   d
0  0  0   0   1
1  1  2   5   1
2  2  4  10   4
3  3  6  15  27

## if there are missing values, Pandas will fill them in with NaN

In [45]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b' : 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [46]:
pd.DataFrame({'population': population, 
              'area': area})

population    area
California    38500000  424000
Texas         26000000  700000
New York      20000000  142000
Florida       19000000  170000
Illinois      12000000  150000

In [47]:
pd.DataFrame(np.random.rand(3, 2),
            columns=['foo', 'bar'],
            index=['a', 'b','c'])

foo       bar
a  0.183850  0.568306
b  0.897481  0.993369
c  0.107681  0.199097

In [49]:
pd.DataFrame(np.random.rand(3, 2),
            columns=['foo', 'bar'],) #if index is omitted integers will be used

foo       bar
0  0.569337  0.967056
1  0.810265  0.249412
2  0.374962  0.260592

In [52]:
A = np.zeros(3, dtype=[('A', 'i8'),('B', 'f8')])
A #integer, and f8

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [51]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [53]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [54]:
ind[1]

3

In [55]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [56]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [58]:
#ind[1] = 0 can't do this operation, as indices are immutable

In [59]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [62]:
indA & indB # intersection

Int64Index([3, 5, 7], dtype='int64')

In [63]:
indA | indB # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [64]:
indA ^ indB # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

In [65]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index =['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [66]:
data['b']

0.5

In [67]:
'a' in data

True

In [68]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [69]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [71]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [72]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [73]:
#slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [74]:
#masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [75]:
#fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [76]:
data = pd.Series(['a', 'b', 'c'], 
                index = [1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [77]:
# explicit index when indexing
data[1]

'a'

In [78]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [79]:
data

1    a
3    b
5    c
dtype: object

# can be slightly confusing based on how the indexing is setup. We need to instinctively be careful.

### using .loc allows indexing and slicing that always references the explicit index

In [80]:
data.loc[1]

'a'

In [81]:
data.loc[1:3]

1    a
3    b
dtype: object

### then using .iloc is for indexing and slicing that references the implicit Python-style index 

In [82]:
data.iloc[0]

'a'

In [83]:
data.iloc[1]

'b'

In [85]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [92]:
data.iloc[0:3]

1    a
3    b
5    c
dtype: object

In [93]:
area = pd.Series({'California': 424000,
                 'Texas': 700000,
                  'New York': 140000,
                  'Florida': 170000,
                 'Illinois': 150000})
pop = pd.Series({'California': 38000000,
                'Texas': 26500000,
                'New York': 19650000,
                'Florida': 19500000,
                'Illinois': 1300000})
data = pd.DataFrame({'area': area, 'pop':pop})
data

area       pop
California  424000  38000000
Texas       700000  26500000
New York    140000  19650000
Florida     170000  19500000
Illinois    150000   1300000

In [94]:
data['area']

California    424000
Texas         700000
New York      140000
Florida       170000
Illinois      150000
Name: area, dtype: int64

In [95]:
data.area

California    424000
Texas         700000
New York      140000
Florida       170000
Illinois      150000
Name: area, dtype: int64

In [96]:
data.area is data['area']

True

In [98]:
data.pop is data['pop'] #for example, DataFrame has a pop() method, so data.pop will point to this rather than the 
# "pop" column and alas, raises a False

False

In [100]:
data['density'] = data['pop'] / data['area'] # it's good practice to do our columns like this
data

area       pop     density
California  424000  38000000   89.622642
Texas       700000  26500000   37.857143
New York    140000  19650000  140.357143
Florida     170000  19500000  114.705882
Illinois    150000   1300000    8.666667

In [101]:
data.values

array([[4.24000000e+05, 3.80000000e+07, 8.96226415e+01],
       [7.00000000e+05, 2.65000000e+07, 3.78571429e+01],
       [1.40000000e+05, 1.96500000e+07, 1.40357143e+02],
       [1.70000000e+05, 1.95000000e+07, 1.14705882e+02],
       [1.50000000e+05, 1.30000000e+06, 8.66666667e+00]])

In [102]:
data.T #transpose the DataFrame

California         Texas      New York       Florida      Illinois
area     4.240000e+05  7.000000e+05  1.400000e+05  1.700000e+05  1.500000e+05
pop      3.800000e+07  2.650000e+07  1.965000e+07  1.950000e+07  1.300000e+06
density  8.962264e+01  3.785714e+01  1.403571e+02  1.147059e+02  8.666667e+00

In [103]:
data.values[0]

array([4.24000000e+05, 3.80000000e+07, 8.96226415e+01])

In [104]:
data['area']

California    424000
Texas         700000
New York      140000
Florida       170000
Illinois      150000
Name: area, dtype: int64

In [111]:
data.iloc[:3, :2]

area       pop
California  424000  38000000
Texas       700000  26500000
New York    140000  19650000

In [110]:
data.loc[:'New York',:'pop']

area       pop
California  424000  38000000
Texas       700000  26500000
New York    140000  19650000

In [112]:
data.ix[:3, :'pop']

/Users/davescott/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area       pop
California  424000  38000000
Texas       700000  26500000
New York    140000  19650000

In [116]:
data.loc[data.density > 85, ['pop', 'density']]

pop     density
California  38000000   89.622642
New York    19650000  140.357143
Florida     19500000  114.705882

In [118]:
data.iloc[0, 2] = 90
data

area       pop     density
California  424000  38000000   90.000000
Texas       700000  26500000   37.857143
New York    140000  19650000  140.357143
Florida     170000  19500000  114.705882
Illinois    150000   1300000    8.666667

In [120]:
data.iloc[4, 2] = 10
data

area       pop     density
California  424000  38000000   90.000000
Texas       700000  26500000   37.857143
New York    140000  19650000  140.357143
Florida     170000  19500000  114.705882
Illinois    150000   1300000   10.000000

In [121]:
data['area/density'] = data['area'] / data['density'] # it's good practice to do our columns like this
data

area       pop     density  area/density
California  424000  38000000   90.000000   4711.111111
Texas       700000  26500000   37.857143  18490.566038
New York    140000  19650000  140.357143    997.455471
Florida     170000  19500000  114.705882   1482.051282
Illinois    150000   1300000   10.000000  15000.000000

In [129]:
data.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [130]:
data.columns

Index(['area', 'pop', 'density', 'area/density'], dtype='object')

In [137]:
data.columns = ['area', 'pop', 'populationdensity', 'area/density']
data

area       pop  populationdensity  area/density
California  424000  38000000          90.000000   4711.111111
Texas       700000  26500000          37.857143  18490.566038
New York    140000  19650000         140.357143    997.455471
Florida     170000  19500000         114.705882   1482.051282
Illinois    150000   1300000          10.000000  15000.000000

In [138]:
data['Florida':'Illinois']

area       pop  populationdensity  area/density
Florida   170000  19500000         114.705882   1482.051282
Illinois  150000   1300000          10.000000  15000.000000

In [139]:
data[1:3]

area       pop  populationdensity  area/density
Texas     700000  26500000          37.857143  18490.566038
New York  140000  19650000         140.357143    997.455471

In [140]:
data[data.populationdensity > 100]

area       pop  populationdensity  area/density
New York  140000  19650000         140.357143    997.455471
Florida   170000  19500000         114.705882   1482.051282

In [141]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [142]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                 columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [144]:
np.exp(ser) # use np ufuncs, however, maintain Pandas DataFrames

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [145]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [147]:
area = pd.Series({'Alaska': 1723337, 'Texas': 700000, 'California': 424000}, name = 'area')
population = pd.Series({'California': 38330000, 'Texas': 26500000, 'New York': 19650000}, name = 'population')
#imagine there are two different data sources with mismatched columns and values

In [148]:
population / area

Alaska              NaN
California    90.400943
New York            NaN
Texas         37.857143
dtype: float64

In [149]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [150]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

# filling in NaN

In [151]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### index alignment

In [159]:
A = pd.DataFrame(rng.randint(0, 20, (2,2)),
                columns=list('AB'))
A

A  B
0  3  1
1  5  9

In [160]:
B = pd.DataFrame(rng.randint(0, 10, (3,3)),
                columns=list('BAC'))
B

B  A  C
0  3  5  1
1  9  1  9
2  3  7  6

In [161]:
A + B

A     B   C
0  8.0   4.0 NaN
1  6.0  18.0 NaN
2  NaN   NaN NaN

In [162]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   8.0   4.0   5.5
1   6.0  18.0  13.5
2  11.5   7.5  10.5

In [166]:
A = rng.randint(10, size=(3,4))
A

array([[9, 6, 9, 8],
       [6, 8, 7, 1],
       [0, 6, 6, 7]])

In [167]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-3,  2, -2, -7],
       [-9,  0, -3, -1]])

In [168]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -3  2 -2 -7
2 -9  0 -3 -1

# if you want to make operations columnwise, use axes, appropriately

In [169]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0  3  0  3  2
1 -2  0 -1 -7
2 -6  0  0  1

# Handling Missing Data

In [170]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [172]:
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print() #object has much overhead and is significantly slower

dtype = object
58.6 ms ± 226 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
945 µs ± 14.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



In [175]:
#vals1.sum() running sum over an array with objects results in an error
#addition between an integer and an object (None) is undefined

# Handling NaN

In [177]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

#### NaN is a bit like a virus. It will affect any other object it touches

In [178]:
1 + np.nan

nan

In [179]:
0 * np.nan

nan

In [180]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

### however, there are some operations that will ignore these missing values

In [181]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

#### Pandas is built to handle None and NaN very similarly

In [182]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [183]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [185]:
x[0] = None
x #automatically changes to floating point array

0    NaN
1    1.0
dtype: float64

## detecting nulls

In [186]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [187]:
data[data.notnull()]

0        1
2    hello
dtype: object

# dropping null values

In [189]:
data.dropna()

0        1
2    hello
dtype: object

In [190]:
df = pd.DataFrame([[1, np.nan, 2],
                  [2, 3, 5],
                  [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

## when we are working with a DataFrame, we can only drop fully rows or columns, not individual elements. Therefore, we are only able to drop full rows or full columns

### by default, df.dropna() will droo all rows in which any null value is present

In [191]:
df.dropna()

0    1  2
1  2.0  3.0  5

## or, we may utilize column's to drop only relevant columns

In [192]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

## we can also use how='all', which will only drop rows/columns that are all null values

In [194]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [195]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

## the thresh parameter also allows you to specify the minimum nuimber of non-null values for the row/column to be kept

In [196]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [197]:
df.dropna(axis='columns', thresh=2)

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

# Filling null values

In [199]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

#### it's very easy to fill NaN entiries with a single value, such as zero:

In [200]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [201]:
# forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [202]:
#back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [203]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

## DataFrames are similar, however, we need to specify an axis on which the fills take place

In [205]:
df.fillna(method='ffill', axis=1) #if a previous value is not available, the NaN value remains

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

# Multiindexing : heirarchical indexing

In [206]:
index = [('California', 2000), ('California', 2010),
        ('New York', 2000), ('New York', 2010),
        ('Texas', 2000), ('Texas', 2010)]
populations = [33870000, 37250000,
              18900000, 19400000,
              20869000, 25150000]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33870000
(California, 2010)    37250000
(New York, 2000)      18900000
(New York, 2010)      19400000
(Texas, 2000)         20869000
(Texas, 2010)         25150000
dtype: int64

In [207]:
pop[('California', 2010):('Texas', 2000)]

(California, 2010)    37250000
(New York, 2000)      18900000
(New York, 2010)      19400000
(Texas, 2000)         20869000
dtype: int64

### however, if we need to select all values from 2010, things get messy and slow

In [209]:
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37250000
(New York, 2010)      19400000
(Texas, 2010)         25150000
dtype: int64

### however, we have better options with Pandas MultiIndex

In [212]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [214]:
pop = pop.reindex(index)
pop #cleanly multiindexed

California  2000    33870000
            2010    37250000
New York    2000    18900000
            2010    19400000
Texas       2000    20869000
            2010    25150000
dtype: int64

In [215]:
pop[:, 2010]

California    37250000
New York      19400000
Texas         25150000
dtype: int64

In [216]:
pop[:, 2010]

California    37250000
New York      19400000
Texas         25150000
dtype: int64

In [217]:
pop['California']

2000    33870000
2010    37250000
dtype: int64

## the unstack() method will quickly convert a multiply indexed Series into a conventionally indexed DataFrame:

In [218]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33870000  37250000
New York    18900000  19400000
Texas       20869000  25150000

In [220]:
pop_df.stack() # we have a convenient reverse option

California  2000    33870000
            2010    37250000
New York    2000    18900000
            2010    19400000
Texas       2000    20869000
            2010    25150000
dtype: int64

# MultiIndexing morale: conveniently have three, four, or more dimensions in a single Series or DataFrame

In [221]:
pop_df = pd.DataFrame({'total': pop,
                      'under18': [9267000, 9285000, 
                                 4686000, 4318000, 
                                 5900000, 6879000]})
pop_df

total  under18
California 2000  33870000  9267000
           2010  37250000  9285000
New York   2000  18900000  4686000
           2010  19400000  4318000
Texas      2000  20869000  5900000
           2010  25150000  6879000

In [223]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack() #fraction of people under 18 in each state, during each year

2000      2010
California  0.273605  0.249262
New York    0.247937  0.222577
Texas       0.282716  0.273519

## methods of Multiindex Creation

In [226]:
df = pd.DataFrame(np.random.rand(4,2), 
                 index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                 columns=['data1', 'data2'])
df

data1     data2
a 1  0.776308  0.886261
  2  0.607998  0.720278
b 1  0.284713  0.850545
  2  0.989590  0.035421

In [227]:
data = {('California', 2000): 33840000, ('California', 2010): 37500000,
        ('New York', 2000): 18975000, ('New York', 2010): 19400000,
        ('Texas', 2000): 20850000, ('Texas', 2010): 25100000}
pd.Series(data)
        

California  2000    33840000
            2010    37500000
New York    2000    18975000
            2010    19400000
Texas       2000    20850000
            2010    25100000
dtype: int64

In [229]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]]) #from arrays

MultiIndex(levels=[['a', 'b'], [1, 2]],
           codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [231]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)]) #from tuples

MultiIndex(levels=[['a', 'b'], [1, 2]],
           codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [232]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]]) # from Cartesian products of single indices

MultiIndex(levels=[['a', 'b'], [1, 2]],
           codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [235]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
             codes=[[0,0,1,1], [0,1,0,1]]) # index argument

MultiIndex(levels=[['a', 'b'], [1, 2]],
           codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

## MultiIndex level names

In [237]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33870000
            2010    37250000
New York    2000    18900000
            2010    19400000
Texas       2000    20869000
            2010    25150000
dtype: int64

In [241]:
# heirarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                  names=['year', 'visit'])
columns=pd.MultiIndex.from_product([['Bob', 'Guido','Sue'], ['HR', 'Temp']],
                                  names=['subject', 'type'])
# mock some data
data = np.round(np.random.randn(4,6), 1)
data[:, ::2] *= 10
data += 37
# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data    #four dimensional data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      39.0  37.4  44.0  35.5  20.0  35.1
     2      51.0  36.8  35.0  36.6  57.0  36.9
2014 1      30.0  36.3  25.0  36.7  40.0  35.4
     2      36.0  36.6  15.0  36.4  35.0  38.1

In [242]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      44.0  35.5
     2      35.0  36.6
2014 1      25.0  36.7
     2      15.0  36.4

In [243]:
pop

state       year
California  2000    33870000
            2010    37250000
New York    2000    18900000
            2010    19400000
Texas       2000    20869000
            2010    25150000
dtype: int64

In [244]:
pop['California', 2000]

33870000

In [245]:
pop['California']

year
2000    33870000
2010    37250000
dtype: int64

In [246]:
pop.loc['California':'New York']

state       year
California  2000    33870000
            2010    37250000
New York    2000    18900000
            2010    19400000
dtype: int64

In [247]:
pop[:, 2000]

state
California    33870000
New York      18900000
Texas         20869000
dtype: int64

In [250]:
pop[pop > 22000000]

state       year
California  2000    33870000
            2010    37250000
Texas       2010    25150000
dtype: int64

In [253]:
pop[['California', 'Texas']]

state       year
California  2000    33870000
            2010    37250000
Texas       2000    20869000
            2010    25150000
dtype: int64

In [254]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      39.0  37.4  44.0  35.5  20.0  35.1
     2      51.0  36.8  35.0  36.6  57.0  36.9
2014 1      30.0  36.3  25.0  36.7  40.0  35.4
     2      36.0  36.6  15.0  36.4  35.0  38.1

In [255]:
health_data['Guido', 'HR']

year  visit
2013  1        44.0
      2        35.0
2014  1        25.0
      2        15.0
Name: (Guido, HR), dtype: float64

In [258]:
health_data.iloc[:4,:2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      39.0  37.4
     2      51.0  36.8
2014 1      30.0  36.3
     2      36.0  36.6

In [259]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        39.0
      2        51.0
2014  1        30.0
      2        36.0
Name: (Bob, HR), dtype: float64

In [261]:
#health_data.iloc[(:, 1), (:, 'HR')] creating a tuple will result in an error

### instead, can use slice() or IndexSlice

In [262]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      39.0  44.0  20.0
2014 1      30.0  25.0  40.0

In [263]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names =['char', 'int']
data

char  int
a     1      0.403262
      2      0.676490
c     1      0.164400
      2      0.140594
b     1      0.517947
      2      0.731077
dtype: float64

### taking a partial slice of this array will result in an error

In [265]:
try:
    data['a': 'b']
except KeyError as e:
        print(type(e))
        print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [266]:
data = data.sort_index()
data #use sort.index() or sortlevel() to sort MultiIndex

char  int
a     1      0.403262
      2      0.676490
b     1      0.517947
      2      0.731077
c     1      0.164400
      2      0.140594
dtype: float64