In [1]:
import numpy

In [2]:
numpy.__version__

'1.16.2'

In [3]:
import numpy as np

# remember, we can call all useful portions of numpy by doing np.<tab>

In [4]:
np.<tab (that is :)>

SyntaxError: invalid syntax (<ipython-input-4-4fee3d732ec3>, line 1)

In [5]:
np?

In [6]:
result = 0
for i in range (100):
    result += i

In [7]:
x = 4
x = "four"

In [8]:
x

'four'

In [10]:
L = list(range(10))

In [11]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
type(L[0])

int

In [13]:
L2 = [str(c) for c in L]

In [14]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [15]:
type(L2[0])

str

In [16]:
L3 = [True, "2", 3.0, 4]

In [17]:
[type(item) for item in L3]

[bool, str, float, int]

In [18]:
import array
L = list(range(100))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
[type(item) for item in A]

[int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int]

In [23]:
import numpy as np
import random as random

In [24]:
# integer array:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [27]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [30]:
np.array([3.14, 4, 2, 5])

array([3.14, 4.  , 2.  , 5.  ])

In [31]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

#### Can manually set the data type

In [32]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [33]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.full((2,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

# create an array with a linear sequence starting at 0, ending at 20, stepping by 2

In [37]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# create an array with five values evenly spaced between 0 and 1

In [38]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [40]:
np.random.random((3,3)) #uniformly distributed

array([[0.73675036, 0.7447149 , 0.91562088],
       [0.75745276, 0.04226016, 0.20463023],
       [0.83879999, 0.88050979, 0.06157803]])

In [42]:
np.random.normal(0,1,(3,3)) #normally distributed

array([[ 0.0796014 ,  1.16895651, -0.27797173],
       [ 0.45345624, -2.17488365, -2.27085505],
       [-1.03245517,  0.08806443, -1.06775812]])

# Create a matrice of normally distributed random values with 0 and standard deviation of one

In [43]:
np.random.randint(0,10,(4,4))

array([[3, 3, 6, 3],
       [1, 4, 8, 1],
       [1, 6, 4, 2],
       [3, 5, 5, 8]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.empty(3)

array([1., 1., 1.])

### there are over 19 types of "standard" NumPy data types. Many more advanced ones are possible

# manipulating arrays

In [46]:
import numpy as np
np.random.seed(0)

In [47]:
x1 = np.random.randint(10, size=6) #1-d
x2 = np.random.randint(10, size=(3,4)) #2-d
x3 = np.random.randint(10, size=(3,4,5)) #2-d

In [48]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [49]:
print("x3 dtype:", x3.dtype)

x3 dtype: int64


In [50]:
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


# accessing individual elements in an array

In [51]:
x1 

array([5, 0, 3, 3, 7, 9])

In [52]:
x1[0]

5

In [53]:
x1[4]

7

In [54]:
x1[-1]

9

In [55]:
x1[-2]

7

In [56]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [57]:
x2[0,0]

3

In [58]:
x2[2, 0]

1

In [59]:
x2[2, -1]

7

In [60]:
x2[-1,-1]

7

In [61]:
x2[-2, -1]

8

In [64]:
x2[0, 0]=12 #modifying elements

In [63]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# we can't input a floating point to an array since it's a fixed type 注意安全！

In [65]:
x1[0] = 3.14159

In [66]:
x1

array([3, 0, 3, 3, 7, 9])

In [68]:
#^ truncated

# general format for accessing arrays x[start:stop:step]

In [71]:
x = np.arange(10)

In [72]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
x[:5]

array([0, 1, 2, 3, 4])

In [74]:
x[0:5]

array([0, 1, 2, 3, 4])

In [75]:
x[5:]

array([5, 6, 7, 8, 9])

In [76]:
x[5:10]

array([5, 6, 7, 8, 9])

In [77]:
x[4:7]

array([4, 5, 6])

In [79]:
x[::2] #stepsize of 2

array([0, 2, 4, 6, 8])

In [81]:
x[1::2] #every other element starting at 1

array([1, 3, 5, 7, 9])

# when the step size is negative, the defaults for staert and stop are swapped

In [82]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [83]:
x[5::-2]

array([5, 3, 1])

# multidimensional slicing

In [84]:
x2 

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2