In [1]:
import numpy

In [2]:
numpy.__version__

'1.16.2'

In [3]:
import numpy as np

# remember, we can call all useful portions of numpy by doing np.<tab>

In [4]:
np.<tab (that is :)>

SyntaxError: invalid syntax (<ipython-input-4-4fee3d732ec3>, line 1)

In [5]:
np?

In [6]:
result = 0
for i in range (100):
    result += i

In [7]:
x = 4
x = "four"

In [8]:
x

'four'

In [10]:
L = list(range(10))

In [11]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
type(L[0])

int

In [13]:
L2 = [str(c) for c in L]

In [14]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [15]:
type(L2[0])

str

In [16]:
L3 = [True, "2", 3.0, 4]

In [17]:
[type(item) for item in L3]

[bool, str, float, int]

In [18]:
import array
L = list(range(100))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
[type(item) for item in A]

[int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int]

In [23]:
import numpy as np
import random as random

In [24]:
# integer array:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [27]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [30]:
np.array([3.14, 4, 2, 5])

array([3.14, 4.  , 2.  , 5.  ])

In [31]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

#### Can manually set the data type

In [32]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [33]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.full((2,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

# create an array with a linear sequence starting at 0, ending at 20, stepping by 2

In [37]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# create an array with five values evenly spaced between 0 and 1

In [38]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [40]:
np.random.random((3,3)) #uniformly distributed

array([[0.73675036, 0.7447149 , 0.91562088],
       [0.75745276, 0.04226016, 0.20463023],
       [0.83879999, 0.88050979, 0.06157803]])

In [42]:
np.random.normal(0,1,(3,3)) #normally distributed

array([[ 0.0796014 ,  1.16895651, -0.27797173],
       [ 0.45345624, -2.17488365, -2.27085505],
       [-1.03245517,  0.08806443, -1.06775812]])

# Create a matrice of normally distributed random values with 0 and standard deviation of one

In [43]:
np.random.randint(0,10,(4,4))

array([[3, 3, 6, 3],
       [1, 4, 8, 1],
       [1, 6, 4, 2],
       [3, 5, 5, 8]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.empty(3)

array([1., 1., 1.])

### there are over 19 types of "standard" NumPy data types. Many more advanced ones are possible

# manipulating arrays

In [46]:
import numpy as np
np.random.seed(0)

In [47]:
x1 = np.random.randint(10, size=6) #1-d
x2 = np.random.randint(10, size=(3,4)) #2-d
x3 = np.random.randint(10, size=(3,4,5)) #2-d

In [48]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [49]:
print("x3 dtype:", x3.dtype)

x3 dtype: int64


In [50]:
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


# accessing individual elements in an array

In [51]:
x1 

array([5, 0, 3, 3, 7, 9])

In [52]:
x1[0]

5

In [53]:
x1[4]

7

In [54]:
x1[-1]

9

In [55]:
x1[-2]

7

In [56]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [57]:
x2[0,0]

3

In [58]:
x2[2, 0]

1

In [59]:
x2[2, -1]

7

In [60]:
x2[-1,-1]

7

In [61]:
x2[-2, -1]

8

In [64]:
x2[0, 0]=12 #modifying elements

In [63]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# we can't input a floating point to an array since it's a fixed type 注意安全！

In [65]:
x1[0] = 3.14159

In [66]:
x1

array([3, 0, 3, 3, 7, 9])

In [68]:
#^ truncated

# general format for accessing arrays x[start:stop:step]

In [71]:
x = np.arange(10)

In [72]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
x[:5]

array([0, 1, 2, 3, 4])

In [74]:
x[0:5]

array([0, 1, 2, 3, 4])

In [75]:
x[5:]

array([5, 6, 7, 8, 9])

In [76]:
x[5:10]

array([5, 6, 7, 8, 9])

In [77]:
x[4:7]

array([4, 5, 6])

In [79]:
x[::2] #stepsize of 2

array([0, 2, 4, 6, 8])

In [81]:
x[1::2] #every other element starting at 1

array([1, 3, 5, 7, 9])

# when the step size is negative, the defaults for staert and stop are swapped

In [82]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [83]:
x[5::-2]

array([5, 3, 1])

# multidimensional slicing

In [84]:
x2 

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [86]:
x2[:2, :3] #two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [88]:
x2[:3, ::2] #all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

## reverse dimensions all together

In [89]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

## accessing rows and columns

In [91]:
print(x2[:, 0]) #first column of x2

[12  7  1]


In [93]:
print(x2[0, :]) #first row of x2

[12  5  2  4]


In [94]:
print(x2[0])#to be more efficient with row access, we can get rid of :

[12  5  2  4]


# one of the most important things to realize is when we slice arrays, we are slicing "views" of the array, rather than copies

# Alas, anything that is done to the array outside the main copy will also occur to the main array

In [95]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [96]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [97]:
x2_sub[0,0] = 99

In [98]:
print(x2_sub)

[[99  5]
 [ 7  6]]


In [99]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# this is very important to realize if we are not creating copies of our array

# to explicitly copy an array, we may add the .copy() to the end of the array as such

In [100]:
x2_sub_copy = x2[:2, :2].copy()

In [101]:
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [103]:
x2_sub_copy[0,0] = 5

In [104]:
print(x2_sub_copy)

[[5 5]
 [7 6]]


In [105]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## x2 is non-adjusted

In [108]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


 # reshaping arrays

### you can use either the reshape method or newaxis keyword

In [109]:
x = np.array([1, 2, 3])

In [110]:
# row vector via reshape

In [111]:
x.reshape((1,3))

array([[1, 2, 3]])

In [112]:
print(x)

[1 2 3]


In [113]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [114]:
print(x)

[1 2 3]


In [115]:
x.reshape(1,3)

array([[1, 2, 3]])

In [116]:
print(x)

[1 2 3]


In [117]:
# row vector via newaxis

In [118]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [119]:
#column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [120]:
#column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array concatenation and splitting (VERY IMPORTANT)

## np.concatenate, np.vstack, np.hstack

In [124]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [125]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [126]:
z = [11, 22, 33]

In [127]:
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 11, 22, 33])

In [128]:
grid = np.array([[1,2,3], [4,5,6]])

In [130]:
#concatenate along first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [131]:
#concatenate along second axis (zero-axis)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# to work with arrays of mixed dimensions, it may be easier to use np.vstack (vertical stack) or np.hstack (horizontal stack)

In [139]:
%debug
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])

> <ipython-input-138-e67923d20364>(3)<module>()
      1 get_ipython().run_line_magic('debug', '')
      2 x = np.array([1, 2, 3])
----> 3 grid = np.array([9, 8, 7], [6, 5, 4])

ipdb> quit


In [140]:
y = np.vstack([x, grid])

In [142]:
np.vstack([x, grid]) #vertically stack arrays

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [145]:
y = np.array([[99], [99]])# horizontally stack arrays

In [146]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# additionally, np.dstack may be used to stack in the third dimension

# splitting arrays use: np.split, np.hsplit, np.vsplit

In [147]:
x = [1, 2, 3, 99 , 99, 3, 2, 1]

In [148]:
x1, x2, x3 = np.split(x,[3,5])

In [149]:
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [151]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [152]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [153]:
print(upper)

[[0 1 2 3]
 [4 5 6 7]]


In [163]:
shang, xia = np.hsplit(grid, 2)
print(xia)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [164]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# use np.dsplit for splitting arrays along third axis

In [165]:
np.random.seed(0)

In [167]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/ values[i]
    return output

values = np.random.randint(1, 10, size=5)
print(values)
compute_reciprocals(values)

[4 6 3 5 8]


array([0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [168]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.8 s ± 36.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# this above method is extremely slow. We need to find more efficient operations.

# let's introduce UFuncs - essentially vectorized options

In [169]:
print(compute_reciprocals(values))

[0.25       0.16666667 0.33333333 0.2        0.125     ]


In [170]:
print(1.0 / values)

[0.25       0.16666667 0.33333333 0.2        0.125     ]


In [171]:
%timeit (1.0 / big_array)

1.08 ms ± 29.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# as we can see, the vectorized function compared to the loop gives speeds that are barely comparable.

In [174]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [175]:
print(np.arange(5))

[0 1 2 3 4]


In [176]:
print(np.arange(1,6))

[1 2 3 4 5]


# also useful for multidimensional arrays

In [178]:
x = np.arange(9).reshape((3,3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

# moral of the story is this: vectors are ALWAYS faster than loops. Anytime we see a loop we should ask ourselves whether this can be replaced by vectors.

# unary ufuncs: operate on a single input and binary ufuncs, operate on two inputs

## array arithmetic

In [180]:
x = np.arange(4)
print(x)

[0 1 2 3]


In [181]:
print("x =", x)

x = [0 1 2 3]


In [183]:
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 5 =", x * 5)
print("x /2 5 =", x / 2)
print("x // 2 =", x // 2) # floor division

x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 5 = [ 0  5 10 15]
x /2 5 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [184]:
print("-x  =", -x )
print("x ** 2 =", x ** 2)
print("x % 2 =", x % 2)

-x  = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


# these operations can also be easily combined

In [191]:
print(x)
-(0.5*x + 3) ** 2

[0 1 2 3]


array([ -9.  , -12.25, -16.  , -20.25])

# it's also useful to note that although there are these commands, there are wrappers that can conveniently do these operations for us

In [192]:
np.add(x,2)

array([2, 3, 4, 5])

In [194]:
print(x)

[0 1 2 3]


In [195]:
x = np.array([-2 , 1, 0 , 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [196]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [197]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [198]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

## also capable of handling complex numbers

# trigonometric functions

In [199]:
theta = np.linspace(0, np.pi, 3)

In [200]:
print("theta =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))

theta = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [202]:
x = [-1, 0, 1]
print("x           =", x)
print("arcsin(x) =", np.arcsin(x))
print("arccos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))

x           = [-1, 0, 1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


# exponents and logarithms

In [203]:
x = [1 , 2, 3]

In [204]:
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [205]:
x = [1, 2, 4, 10]
print("x     =", x)
print("ln(x)   =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x)   =", np.log10(x))

x     = [1, 2, 4, 10]
ln(x)   = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x)   = [0.         0.30103    0.60205999 1.        ]


# maintaining precision with very small input:

In [206]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1=", np.expm1(x))
print("log(1+x) =", np.log1p(x))

exp(x) - 1= [0.         0.0010005  0.01005017 0.10517092]
log(1+x) = [0.         0.0009995  0.00995033 0.09531018]


# obscure functions

In [207]:
from scipy import special

In [210]:
# Gamma functions
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln| gamma(x) =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x,2))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln| gamma(x) = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [211]:
# Error function
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfcinv(x) =", special.erfinv(x))

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfcinv(x) = [0.         0.27246271 0.73286908        inf]


# specifying ouputs

In [212]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [213]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [214]:
y[::2] = 2 ** x

In [215]:
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


# aggregates - reducing arrays

In [216]:
x = np.arange(1, 6)
print(x)

[1 2 3 4 5]


In [217]:
np.add.reduce(x)

15

In [218]:
np.multiply.reduce(x)

120

In [219]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [220]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [223]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

# more aggregations

In [224]:
L = np.random.random(100)
sum(L)

51.67294892341679

In [226]:
np.sum(L) # two different ways to sum

51.67294892341681

In [227]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

78.1 ms ± 970 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
351 µs ± 8.68 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# however, it should be noted that these two sum functions are not the same

In [228]:
min(big_array), max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [229]:
np.min(big_array), np.max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [230]:
%timeit min(big_array)
%timeit np.min(big_array)

54.7 ms ± 2.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
349 µs ± 5.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [231]:
print(big_array.min(), big_array.max(), big_array.sum())

7.071203171893359e-07 0.9999997207656334 500216.2680607901


In [232]:
M = np.random.random((3, 4))
print(M)

[[0.18441813 0.71417358 0.76371195 0.11957117]
 [0.37578601 0.11936151 0.37497044 0.22944653]
 [0.07452786 0.41843762 0.99939192 0.66974416]]


In [233]:
M.sum()

5.043540889364842

In [235]:
M.min(axis=0) #takes the minimum on each column axis since axis=0

array([0.07452786, 0.11936151, 0.37497044, 0.11957117])

In [236]:
M.max(axis=1)

array([0.76371195, 0.37578601, 0.99939192])